services:
  - type: web
    name: sasta-safar-backend
    env: python
    rootDir: Sasta-safar-main-main/backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
